FROM python:3.7

ENV MODE=PRODUCTION

COPY ./requirements.txt requirements.txt

RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt

COPY . /sheroa3

WORKDIR /sheroa3

ENTRYPOINT [ "uwsgi", "--ini", "uwsgi.ini"]